### ISSUE TITLE
Lo has resuelto bien, pero este valor de la media query no lo he visto mucho en proyectos

### ISSUE THREAD

**Issue by itacademyReact** [marnauortega/react-sprint-1#1]
Los que aparecen en este blog son más habituales:

https://www.onlinedesignteacher.com/2015/01/css3-media-queries-for-responsive_81.html

https://github.com/marnauortega/react-sprint-1/blob/37cbf6d54dcca2ed0285a3107ff1d5f46241c0ae/nivell-3/style.css#L306

**Comment by marnauortega** [comment]
Hm, es verdad. La verdad es que acostumbro a poner los media queries en medidas no habituales, pero no lo hago arbitrariamente. Lo hago teniendo en cuenta en qué punto el contenido deja de verse de manera óptima.

He encontrado un post (bastante antiguo) enlazado en CSS Tricks que comentaba justamente esto:

...we have slowly moved away from device specific breakpoints in favour of content specific breakpoints, i.e. adding a breakpoint when the content is no longer easy to consume.

With this fundamental shift in thinking we no longer have to fear a new device — a new iPhone width — because we've already fixed our sites to work everywhere.

https://ui.dev/rwd/articles/why-you-dont-need-device-specific-breakpoints#responsive-design-at-its-best

Tiene sentido, no?
